# Generated by Django 5.0.1 on 2024-03-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('process', models.TextField()),
                ('ingredients', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
